POST http://localhost:3000/api/users/
Content-Type: application/json

{ 
  "username": "ismperort",
  "name": "Ismael",
  "surname": "Pérez Ortiz",
  "password": "s1st3m4s",
  "email": "ismperort@alum.us.es",
  "bio": "This is just a test"
}